name: Update Pointers

on:
  push:
    tags:
      - latest

jobs:
  set-new-latest:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Determine Version Tag
        id: get-version
        run: |
          # Fetch all tags (ensures we have complete tag data)
          git fetch --tags

          # Get the commit that 'latest' tag is pointing to
          TARGET_COMMIT=$(git rev-parse HEAD)

          # Find all tags pointing at this commit
          TAGS=$(git tag --points-at "$TARGET_COMMIT")

          # Filter for semantic version tags (vX.Y.Z)
          VERSION_TAG=$(echo "$TAGS" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)

          # If no version tag found, exit with failure
          if [[ -z "$VERSION_TAG" ]]; then
            echo "❌ Commit is not a release (no semantic version tag found)"
            exit 1
          fi

          # Output the found version tag
          echo "✅ Version tag found: $VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> "$GITHUB_ENV"

      - name: Updating latest tag
        run: |
          echo "Doing some updating of the latest tag... somewhere..."

      - name: Update Repository Variable
        if: success()
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh variable set LATEST_VERSION --body "$VERSION_TAG"
