name: Update Pointers

on:
  push:
    tags:
      - stable

jobs:
  set-new-stable:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Fetch all tags
        run: git fetch --tags
   
      - name: Check if commit is tagged as a valid release
        id: check-release
        run: |
          # Get the commit that 'stable' tag is pointing to
          TARGET_COMMIT=$(git rev-parse HEAD)
          echo "The commit for 'stable' tag is: $TARGET_COMMIT"
          # Find all tags pointing at this commit
          TAGS=$(git tag --points-at "$TARGET_COMMIT")

          # Filter for semantic version tags (vX.Y.Z)
          VERSION_TAG=$(echo "$TAGS" | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' | sort -V | tail -n 1)

          # If no version tag found, fail the workflow and delete 'stable'
          if [[ -z "$VERSION_TAG" ]]; then
            echo "❌ Commit is not a release (no semantic version tag found)"
            git tag -d stable  # Delete the 'stable' tag locally
            git push origin :refs/tags/stable  # Delete the 'stable' tag remotely
            exit 1  # Exit the workflow to prevent further steps
          fi

          echo "✅ Version tag found: $VERSION_TAG"
          echo "VERSION_TAG=$VERSION_TAG" >> "$GITHUB_ENV"

      - name: Generate badge
        run: |
          echo "{ \"schemaVersion\": 1, \"label\": \"Stable Release\", \"message\": \"${{ env.VERSION_TAG }}\", \"color\": \"blue\" }" > stable.json
  
      - name: Upload badge as artifact  
        uses: actions/upload-artifact@v4
        with:
          name: stable-release-badge
          path: stable.json
  
        # Optional: Update a Gist to provide a badge URL
      - name: Update Gist (Optional)
        if: secrets.GIST_ID_STABLE != ''
        run: |
          curl -X PATCH -H "Authorization: token ${{ secrets.GIST_TOKEN_STABLE }}" \
          -d "{\"files\": {\"stable.json\": {\"content\": \"$(cat stable.json)\"}}}" \
          https://api.github.com/gists/${{ secrets.GIST_ID_STABLE }}

      - name: Updating stable tag
        if: success()
        run: |
          echo "Doing some updating of the stable tag... somewhere..."

