name: Module C Test

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/test_module_c.yml'
      - 'some_package/**'
      - 'tests/module_c/**'
      - 'tests/conftest.py  '

jobs:
  test:
    runs-on: ubuntu-latest  # Could replace with self-hosted
    if: github.event_name == 'pull_request' 
    steps:
      - name: Cleanup workspace
        run: |
          sudo rm -rf $GITHUB_WORKSPACE/* || true

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0 

      - name: Prepare workspace
        run: | 
          echo "Preparing workspace..."
     
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'  # Use the desired Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run tests
        if: success()
        run: |
          pytest tests/module_c --capture=no --tb=short
          
  